### ISSUE TITLE
차트, 호버 기능 구현

### ISSUE THREAD

**Issue by hyorimcho** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-3-8#1]
#### 📊 시계열 차트 만들기
- [x] 주어진 JSON 데이터의 `key`값(시간)을 기반으로 시계열 차트를 만들어주세요
- [x]  하나의 차트안에 Area 형태의 그래프와 Bar 형태의 그래프가 모두 존재하는 복합 그래프로 만들어주세요
- [x] Area 그래프의 기준값은 `value_area` 값을 이용해주세요
- [x]  Bar 그래프의 기준값은 `value_bar` 값을 이용해주세요
- [x]  차트의 Y축에 대략적인 수치를 표현해주세요
#### 🖱 호버 기능 구현
- [x]  특정 데이터 구역에 마우스 호버시 `id, value_area, value_bar` 데이터를 툴팁 형태로 제공해주세요

**Comment by hyorimcho** [comment]
#4 best practice 투표 이유

- 중복되는 년도, 월을 분리하는 함수를 만든 것
- 관심사 분리를 잘 한 것

**Comment by raw20** [comment]
#6 best practice 투표 이유
- Recharts 라이브러리  사용으로 각 커스텀 기능들을 컴포넌트로 관리 가능
- 원본 형식에 맞춘 Type 정의
- `Home` 과 `Chart` 컴포넌트 분리로 인해 가독성 향상

**Comment by jhoon9494** [comment]
#8 best practice 투표 이유
- 커스텀 훅을 이용하여 데이터를 사용하는 부분과 구현하는 부분의 관심사에 따른 분리가 적절하게 잘 된 점

**Comment by tnghgks** [comment]
#2 best practice 투표 이유
- 커스텀 툴팁 컴포넌트로 분리로 인한 관심사 분리
- 간결한 코드 구조

**Comment by Noeyso** [comment]
#4 best practice 투표 이유

- 관심사 분리가 잘 돼있는 코드
- 코드의 가독성 (변수명 활용을 잘 하여 의미부여를 명확하게 한 점)

**Comment by bokjunwoo** [comment]
https://github.com/Wanted-PreOnboarding-Team-8/pre-onboarding-9th-3-8/pull/8 best practice 투표 이유
- 커스텀 훅을 이용한 관심사 분리가 된 점

**Comment by greyHairChooseLife** [comment]
#6 best practice 투표 이유

- 페이지 컴포넌트와 차트 컴포넌트를 분리하여 페이지에서 여러 차트를 관리 할 수 있도록 잡은 구조
- data fetch 및 포매팅 과정에서 타입들을 적절히 세팅한 점. (아마도 이후 개발 중에 편리하셨겠죠? 저는 나중에 하자고 미루면서 했는데 오히려 그 때문에 더 불편했던 것 같아요.)
